# Generated by Django 3.1.2 on 2020-10-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0006_profile_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='manager',
        ),
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.ManyToManyField(null=True, related_name='_profile_manager_+', to='UserAuth.Profile'),
        ),
    ]
