# Generated by Django 3.1.2 on 2020-10-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0008_auto_20201030_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='manager',
            field=models.ManyToManyField(null=True, related_name='_profile_manager_+', to='UserAuth.Profile'),
        ),
    ]
