# Generated by Django 3.1.2 on 2020-10-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0009_auto_20201030_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='manager',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='_profile_followers_+', to='UserAuth.Profile'),
        ),
    ]
