# Generated by Django 3.1.2 on 2020-10-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0011_auto_20201030_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
